// Seed data with demo leads for two partners
const now = new Date();
const daysAgo = (n) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString();

export const PARTNERS = [
  {
    id: 'admin_001',
    name: 'Admin',
    email: 'admin@oriafilia.com',
    password: 'admin',
    role: 'Administrateur',
    joinedAt: '2024-01-01',
  },
  {
    id: 'partner_001',
    name: 'Karim',
    email: 'karim@oriafilia.com',
    password: 'demo1234',
    role: 'Partner',
    joinedAt: '2025-01-15',
  },
  {
    id: 'partner_002',
    name: 'Sarah',
    email: 'sarah@oriafilia.com',
    password: 'demo1234',
    role: 'Partner',
    joinedAt: '2025-03-20',
  },
];

export const SEED_LEADS = [
  // Karim's leads
  {
    id: 'lead_001',
    partnerId: 'partner_001',
    contactName: 'Jean Dupont',
    email: 'jean.dupont@email.com',
    phone: '+33 6 12 34 56 78',
    productType: 'Auto',
    situation: 'Résilié non-paiement',
    source: 'Referral',
    estimatedPremium: 1200,
    status: 'Converti',
    commissionRate: 10,
    commissionAmount: 120,
    notes: 'Client intéressé par formule tous risques. A reçu devis compétitif.',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: 'lead_002',
    partnerId: 'partner_001',
    contactName: 'Marie Leblanc',
    email: 'marie.leblanc@email.com',
    phone: '+33 6 98 76 54 32',
    productType: 'Habitation',
    situation: 'Nouveau propriétaire',
    source: 'Website',
    estimatedPremium: 800,
    status: 'Qualifié',
    commissionRate: 8,
    commissionAmount: 0,
    notes: 'Appartement 3 pièces à Lyon. Cherche assurance MRH.',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(8),
  },
  {
    id: 'lead_003',
    partnerId: 'partner_001',
    contactName: 'Pierre Martin',
    email: 'p.martin@email.com',
    phone: '+33 7 11 22 33 44',
    productType: 'Auto',
    situation: 'Jeune conducteur',
    source: 'Cold Call',
    estimatedPremium: 1800,
    status: 'Contacté',
    commissionRate: 10,
    commissionAmount: 0,
    notes: 'Premier véhicule, permis obtenu il y a 3 mois.',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(12),
  },
  {
    id: 'lead_004',
    partnerId: 'partner_001',
    contactName: 'Sophie Bernard',
    email: 'sophie.b@email.com',
    phone: '+33 6 55 44 33 22',
    productType: 'Santé',
    situation: 'Travailleur indépendant',
    source: 'Referral',
    estimatedPremium: 2400,
    status: 'Converti',
    commissionRate: 12,
    commissionAmount: 288,
    notes: 'TNS, besoin couverture complète optique/dentaire.',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
  },
  {
    id: 'lead_005',
    partnerId: 'partner_001',
    contactName: 'Lucas Moreau',
    email: 'lucas.m@email.com',
    phone: '+33 7 22 33 44 55',
    productType: 'Moto',
    situation: 'Malus élevé',
    source: 'Event',
    estimatedPremium: 950,
    status: 'Devis envoyé',
    commissionRate: 10,
    commissionAmount: 0,
    notes: 'Honda CB650R. Bonus/malus 1.5. Cherche tarif compétitif.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(3),
  },
  {
    id: 'lead_006',
    partnerId: 'partner_001',
    contactName: 'Isabelle Petit',
    email: 'isabelle.petit@email.com',
    phone: '+33 6 77 88 99 00',
    productType: 'RC Pro',
    situation: 'Création entreprise',
    source: 'Website',
    estimatedPremium: 3200,
    status: 'Nouveau',
    commissionRate: 15,
    commissionAmount: 0,
    notes: 'SARL consulting IT. Besoin RC Pro + décennale.',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'lead_007',
    partnerId: 'partner_001',
    contactName: 'Thomas Roux',
    email: 'thomas.roux@email.com',
    phone: '+33 7 66 55 44 33',
    productType: 'Auto',
    situation: 'Résilié sinistre',
    source: 'Referral',
    estimatedPremium: 2100,
    status: 'Perdu',
    commissionRate: 10,
    commissionAmount: 0,
    notes: 'Trouvé moins cher ailleurs. Relancer dans 6 mois.',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(35),
  },
  {
    id: 'lead_008',
    partnerId: 'partner_001',
    contactName: 'Emma Laurent',
    email: 'emma.l@email.com',
    phone: '+33 6 11 22 33 44',
    productType: 'Prévoyance',
    situation: 'Salarié cadre',
    source: 'Referral',
    estimatedPremium: 1500,
    status: 'Converti',
    commissionRate: 12,
    commissionAmount: 180,
    notes: 'Prévoyance décès/invalidité. Contrat signé.',
    createdAt: daysAgo(50),
    updatedAt: daysAgo(20),
  },
  {
    id: 'lead_009',
    partnerId: 'partner_001',
    contactName: 'Hugo Garcia',
    email: 'hugo.g@email.com',
    phone: '+33 7 99 88 77 66',
    productType: 'Habitation',
    situation: 'Locataire',
    source: 'Cold Call',
    estimatedPremium: 350,
    status: 'Nouveau',
    commissionRate: 8,
    commissionAmount: 0,
    notes: 'Studio étudiant Paris 11e.',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // Sarah's leads
  {
    id: 'lead_010',
    partnerId: 'partner_002',
    contactName: 'Antoine Duval',
    email: 'antoine.d@email.com',
    phone: '+33 6 44 55 66 77',
    productType: 'Auto',
    situation: 'Bonus 0.50',
    source: 'Referral',
    estimatedPremium: 900,
    status: 'Converti',
    commissionRate: 10,
    commissionAmount: 90,
    notes: 'Bon conducteur, recherche meilleur prix. Contrat signé.',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(10),
  },
  {
    id: 'lead_011',
    partnerId: 'partner_002',
    contactName: 'Camille Leroy',
    email: 'camille.leroy@email.com',
    phone: '+33 7 33 22 11 00',
    productType: 'Santé',
    situation: 'Famille',
    source: 'Website',
    estimatedPremium: 3600,
    status: 'Devis envoyé',
    commissionRate: 12,
    commissionAmount: 0,
    notes: 'Couple + 2 enfants. Besoin couverture hospitalisation.',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
  },
  {
    id: 'lead_012',
    partnerId: 'partner_002',
    contactName: 'Nicolas Fournier',
    email: 'n.fournier@email.com',
    phone: '+33 6 88 77 66 55',
    productType: 'Moto',
    situation: 'Grosse cylindrée',
    source: 'Event',
    estimatedPremium: 1400,
    status: 'Qualifié',
    commissionRate: 10,
    commissionAmount: 0,
    notes: 'Ducati Panigale V4. Garage sécurisé.',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(5),
  },
  {
    id: 'lead_013',
    partnerId: 'partner_002',
    contactName: 'Julie Bonnet',
    email: 'julie.bonnet@email.com',
    phone: '+33 7 55 66 77 88',
    productType: 'Habitation',
    situation: 'Propriétaire maison',
    source: 'Referral',
    estimatedPremium: 1100,
    status: 'Converti',
    commissionRate: 8,
    commissionAmount: 88,
    notes: 'Maison 120m² Bordeaux. Piscine incluse.',
    createdAt: daysAgo(40),
    updatedAt: daysAgo(15),
  },
  {
    id: 'lead_014',
    partnerId: 'partner_002',
    contactName: 'Alexandre Simon',
    email: 'alex.simon@email.com',
    phone: '+33 6 22 11 00 99',
    productType: 'RC Pro',
    situation: 'Auto-entrepreneur',
    source: 'Cold Call',
    estimatedPremium: 500,
    status: 'Nouveau',
    commissionRate: 15,
    commissionAmount: 0,
    notes: 'Consultant marketing digital. Besoin RC Pro basique.',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'lead_015',
    partnerId: 'partner_002',
    contactName: 'Manon Chevalier',
    email: 'manon.c@email.com',
    phone: '+33 7 44 33 22 11',
    productType: 'Auto',
    situation: 'Jeune conductrice',
    source: 'Website',
    estimatedPremium: 1650,
    status: 'Contacté',
    commissionRate: 10,
    commissionAmount: 0,
    notes: 'Renault Clio V. Permis depuis 6 mois.',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(9),
  },
  {
    id: 'lead_016',
    partnerId: 'partner_002',
    contactName: 'David Mercier',
    email: 'david.m@email.com',
    phone: '+33 6 99 00 11 22',
    productType: 'Prévoyance',
    situation: 'Chef entreprise',
    source: 'Referral',
    estimatedPremium: 4200,
    status: 'Perdu',
    commissionRate: 12,
    commissionAmount: 0,
    notes: 'Budget trop élevé. Reviendra peut-être Q3.',
    createdAt: daysAgo(55),
    updatedAt: daysAgo(30),
  },
];

export const PRODUCT_TYPES = ['Auto', 'Moto', 'Habitation', 'Santé', 'Prévoyance', 'RC Pro'];
export const SOURCES = ['Referral', 'Website', 'Event', 'Cold Call', 'Other'];
export const STATUSES = ['NOUVEAU', 'CONTACTE', 'FAUX NUMERO', 'QUALIFIE', 'CONVERTI ET PAYE'];
